MININOTE_VERSION = '0.0.0'

EVERNOTE_NOTEBOOK = 'mininote'

EVERNOTE_CONSUMER_KEY = 'mininoteapp'
EVERNOTE_CONSUMER_SECRET = 'baffba747fee0512'

EVERNOTE_FETCH_THREADS = 20
EVERNOTE_MAX_PAGE_SIZE = 1000

DEVELOPMENT_MODE = True  # If True, use Evernote sandbox

DEFAULT_EDITOR_WIN = 'notepad.exe'
DEFAULT_EDITOR_OTHER = 'sensible-editor'
